USE master;  
GO  
ALTER DATABASE DBVENTAS_WEB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE DBVENTAS_WEB MODIFY NAME = Sistema_Soporte_Matanza;
GO  
ALTER DATABASE Sistema_Soporte_Matanza SET MULTI_USER;
GO